name: Update pages

on:
  workflow_dispatch:
  push:
    paths:
      - 'updater/**'
    branches: [ main ]

jobs:
  update-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'updater/go.mod'
          cache-dependency-path: 'updater/go.sum'

      - name: Test Go
        run: go test ./...
        working-directory: updater

      - name: Build Go
        run: go build
        working-directory: updater

      - name: Run the updater binary to remake files
        run: ./updater
        working-directory: updater

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update"

      - name: Trigger legacy repo to update READMEs to keep in sync
        if: github.ref == 'refs/heads/main'
        run: |
          export GH_GRANTS_TOKEN=${{ secrets.GH_GRANTS_TOKEN }}
          curl -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token $GH_GRANTS_TOKEN" \
          --request POST --data '{"event_type": "TRIGGER_UPDATE"}' \
          https://api.github.com/repos/getlantern/lantern/dispatches
  
